// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBGtkMU4DrL87ToH6IfQEYk6GQU3w6oI',
    appId: '1:165149505163:web:b223e710384b1808b7868e',
    messagingSenderId: '165149505163',
    projectId: 'vasihatnama',
    authDomain: 'vasihatnama.firebaseapp.com',
    storageBucket: 'vasihatnama.firebasestorage.app',
    measurementId: 'G-RPWGNGGZGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vM9D0cPyr1uIJz9eaIXXEf_ZvVctl14',
    appId: '1:165149505163:android:a7e74ea1143395d7b7868e',
    messagingSenderId: '165149505163',
    projectId: 'vasihatnama',
    storageBucket: 'vasihatnama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAtxEiUsZRlz28mBc49BkQmrw04LbBgA',
    appId: '1:165149505163:ios:daf2f97e9f5d8dfdb7868e',
    messagingSenderId: '165149505163',
    projectId: 'vasihatnama',
    storageBucket: 'vasihatnama.firebasestorage.app',
    iosBundleId: 'com.example.vasihatNama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGAtxEiUsZRlz28mBc49BkQmrw04LbBgA',
    appId: '1:165149505163:ios:daf2f97e9f5d8dfdb7868e',
    messagingSenderId: '165149505163',
    projectId: 'vasihatnama',
    storageBucket: 'vasihatnama.firebasestorage.app',
    iosBundleId: 'com.example.vasihatNama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsBGtkMU4DrL87ToH6IfQEYk6GQU3w6oI',
    appId: '1:165149505163:web:77be4de951e09be3b7868e',
    messagingSenderId: '165149505163',
    projectId: 'vasihatnama',
    authDomain: 'vasihatnama.firebaseapp.com',
    storageBucket: 'vasihatnama.firebasestorage.app',
    measurementId: 'G-J52N76EZPM',
  );

}